// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_robot_status.proto

#ifndef PROTOBUF_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto__INCLUDED
#define PROTOBUF_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
void protobuf_AssignDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();

class Robot_Status;
class Robots_Status;

// ===================================================================

class Robots_Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Robots_Status) */ {
 public:
  Robots_Status();
  virtual ~Robots_Status();

  Robots_Status(const Robots_Status& from);

  inline Robots_Status& operator=(const Robots_Status& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robots_Status& default_instance();

  void Swap(Robots_Status* other);

  // implements Message ----------------------------------------------

  inline Robots_Status* New() const { return New(NULL); }

  Robots_Status* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robots_Status& from);
  void MergeFrom(const Robots_Status& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Robots_Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Robot_Status robots_status = 1;
  int robots_status_size() const;
  void clear_robots_status();
  static const int kRobotsStatusFieldNumber = 1;
  const ::Robot_Status& robots_status(int index) const;
  ::Robot_Status* mutable_robots_status(int index);
  ::Robot_Status* add_robots_status();
  ::google::protobuf::RepeatedPtrField< ::Robot_Status >*
      mutable_robots_status();
  const ::google::protobuf::RepeatedPtrField< ::Robot_Status >&
      robots_status() const;

  // @@protoc_insertion_point(class_scope:Robots_Status)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Robot_Status > robots_status_;
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Robots_Status* default_instance_;
};
// -------------------------------------------------------------------

class Robot_Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Robot_Status) */ {
 public:
  Robot_Status();
  virtual ~Robot_Status();

  Robot_Status(const Robot_Status& from);

  inline Robot_Status& operator=(const Robot_Status& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robot_Status& default_instance();

  void Swap(Robot_Status* other);

  // implements Message ----------------------------------------------

  inline Robot_Status* New() const { return New(NULL); }

  Robot_Status* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robot_Status& from);
  void MergeFrom(const Robot_Status& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Robot_Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 robot_id = 1;
  bool has_robot_id() const;
  void clear_robot_id();
  static const int kRobotIdFieldNumber = 1;
  ::google::protobuf::int32 robot_id() const;
  void set_robot_id(::google::protobuf::int32 value);

  // required bool infrared = 2;
  bool has_infrared() const;
  void clear_infrared();
  static const int kInfraredFieldNumber = 2;
  bool infrared() const;
  void set_infrared(bool value);

  // required bool flat_kick = 3;
  bool has_flat_kick() const;
  void clear_flat_kick();
  static const int kFlatKickFieldNumber = 3;
  bool flat_kick() const;
  void set_flat_kick(bool value);

  // required bool chip_kick = 4;
  bool has_chip_kick() const;
  void clear_chip_kick();
  static const int kChipKickFieldNumber = 4;
  bool chip_kick() const;
  void set_chip_kick(bool value);

  // @@protoc_insertion_point(class_scope:Robot_Status)
 private:
  inline void set_has_robot_id();
  inline void clear_has_robot_id();
  inline void set_has_infrared();
  inline void clear_has_infrared();
  inline void set_has_flat_kick();
  inline void clear_has_flat_kick();
  inline void set_has_chip_kick();
  inline void clear_has_chip_kick();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 robot_id_;
  bool infrared_;
  bool flat_kick_;
  bool chip_kick_;
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Robot_Status* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Robots_Status

// repeated .Robot_Status robots_status = 1;
inline int Robots_Status::robots_status_size() const {
  return robots_status_.size();
}
inline void Robots_Status::clear_robots_status() {
  robots_status_.Clear();
}
inline const ::Robot_Status& Robots_Status::robots_status(int index) const {
  // @@protoc_insertion_point(field_get:Robots_Status.robots_status)
  return robots_status_.Get(index);
}
inline ::Robot_Status* Robots_Status::mutable_robots_status(int index) {
  // @@protoc_insertion_point(field_mutable:Robots_Status.robots_status)
  return robots_status_.Mutable(index);
}
inline ::Robot_Status* Robots_Status::add_robots_status() {
  // @@protoc_insertion_point(field_add:Robots_Status.robots_status)
  return robots_status_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Robot_Status >*
Robots_Status::mutable_robots_status() {
  // @@protoc_insertion_point(field_mutable_list:Robots_Status.robots_status)
  return &robots_status_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Robot_Status >&
Robots_Status::robots_status() const {
  // @@protoc_insertion_point(field_list:Robots_Status.robots_status)
  return robots_status_;
}

// -------------------------------------------------------------------

// Robot_Status

// required int32 robot_id = 1;
inline bool Robot_Status::has_robot_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Robot_Status::set_has_robot_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Robot_Status::clear_has_robot_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Robot_Status::clear_robot_id() {
  robot_id_ = 0;
  clear_has_robot_id();
}
inline ::google::protobuf::int32 Robot_Status::robot_id() const {
  // @@protoc_insertion_point(field_get:Robot_Status.robot_id)
  return robot_id_;
}
inline void Robot_Status::set_robot_id(::google::protobuf::int32 value) {
  set_has_robot_id();
  robot_id_ = value;
  // @@protoc_insertion_point(field_set:Robot_Status.robot_id)
}

// required bool infrared = 2;
inline bool Robot_Status::has_infrared() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Robot_Status::set_has_infrared() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Robot_Status::clear_has_infrared() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Robot_Status::clear_infrared() {
  infrared_ = false;
  clear_has_infrared();
}
inline bool Robot_Status::infrared() const {
  // @@protoc_insertion_point(field_get:Robot_Status.infrared)
  return infrared_;
}
inline void Robot_Status::set_infrared(bool value) {
  set_has_infrared();
  infrared_ = value;
  // @@protoc_insertion_point(field_set:Robot_Status.infrared)
}

// required bool flat_kick = 3;
inline bool Robot_Status::has_flat_kick() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Robot_Status::set_has_flat_kick() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Robot_Status::clear_has_flat_kick() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Robot_Status::clear_flat_kick() {
  flat_kick_ = false;
  clear_has_flat_kick();
}
inline bool Robot_Status::flat_kick() const {
  // @@protoc_insertion_point(field_get:Robot_Status.flat_kick)
  return flat_kick_;
}
inline void Robot_Status::set_flat_kick(bool value) {
  set_has_flat_kick();
  flat_kick_ = value;
  // @@protoc_insertion_point(field_set:Robot_Status.flat_kick)
}

// required bool chip_kick = 4;
inline bool Robot_Status::has_chip_kick() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Robot_Status::set_has_chip_kick() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Robot_Status::clear_has_chip_kick() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Robot_Status::clear_chip_kick() {
  chip_kick_ = false;
  clear_has_chip_kick();
}
inline bool Robot_Status::chip_kick() const {
  // @@protoc_insertion_point(field_get:Robot_Status.chip_kick)
  return chip_kick_;
}
inline void Robot_Status::set_chip_kick(bool value) {
  set_has_chip_kick();
  chip_kick_ = value;
  // @@protoc_insertion_point(field_set:Robot_Status.chip_kick)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5frobocup_5fssl_5frobot_5fstatus_2eproto__INCLUDED
